name: Pruebas Funcionales con Maven

on:
  push:
    branches:
      - develop
      - main
      - test/**    
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Ejecutar pruebas con Maven
      run: mvn test
